### ISSUE TITLE
Failing attempts to create plain http channel while testing against Zato 2.0.0pre0.rev-e11f895d

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato-apitest#11]
Request:

curl --user user:password localhost:11223/zato/json/zato.http-soap.create -d '{"cluster_id":1, "name":"test_channel", "is_active":"true", "connection":"channel", "transport":"plain_http", "is_internal":"false", "url_path":"/my-service/get-key.get-key", "service":"get-key.get-key", "data_format":"json", "method":"GET"}'

Response:

{"zato_env": {"details": "Traceback (most recent call last):\n  File \"\/opt\/zato\/2.0\/zato-server\/src\/zato\/server\/connection\/http_soap\/channel.py\", line 183, in dispatch\n    payload, worker_store, self.simple_io_config, post_data)\n  File \"\/opt\/zato\/2.0\/zato-server\/src\/zato\/server\/connection\/http_soap\/channel.py\", line 323, in handle\n    params_priority=channel_item.params_pri)\n  File \"\/opt\/zato\/2.0\/zato-server\/src\/zato\/server\/service\/**init**.py\", line 326, in update_handle\n    service.handle()\n  File \"\/opt\/zato\/2.0\/zato-server\/src\/zato\/server\/service\/internal\/http_soap.py\", line 177, in handle\n    session.commit()\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/orm\/session.py\", line 765, in commit\n    self.transaction.commit()\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/orm\/session.py\", line 370, in commit\n    self._prepare_impl()\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/orm\/session.py\", line 350, in _prepare_impl\n    self.session.flush()\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/orm\/session.py\", line 1903, in flush\n    self._flush(objects)\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/orm\/session.py\", line 2021, in _flush\n    transaction.rollback(_capture_exception=True)\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/util\/langhelpers.py\", line 57, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/orm\/session.py\", line 1985, in _flush\n    flush_context.execute()\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/orm\/unitofwork.py\", line 370, in execute\n    rec.execute(self)\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/orm\/unitofwork.py\", line 523, in execute\n    uow\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/orm\/persistence.py\", line 64, in save_obj\n    mapper, table, insert)\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/orm\/persistence.py\", line 594, in _emit_insert_statements\n    execute(statement, params)\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/engine\/base.py\", line 720, in execute\n    return meth(self, multiparams, params)\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/sql\/elements.py\", line 317, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/engine\/base.py\", line 817, in _execute_clauseelement\n    compiled_sql, distilled_params\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/engine\/base.py\", line 884, in _execute_context\n    None, None)\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/engine\/base.py\", line 1108, in _handle_dbapi_exception\n    exc_info\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/util\/compat.py\", line 185, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb)\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/engine\/base.py\", line 880, in _execute_context\n    context = constructor(dialect, self, conn, *args)\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/engine\/default.py\", line 572, in _init_compiled\n    param.append(processors[key](compiled_params[key]))\n  File \"\/opt\/zato\/2.0\/eggs\/SQLAlchemy-0.9.4-py2.7-linux-x86_64.egg\/sqlalchemy\/processors.py\", line 53, in boolean_to_int\n    return int(value)\nStatementError: invalid literal for int() with base 10: '' (original cause: ValueError: invalid literal for int() with base 10: '') u'INSERT INTO http_soap (name, is_active, is_internal, connection, transport, host, url_path, method, soap_action, soap_version, data_format, ping_method, pool_size, merge_url_params_req, url_params_pri, params_pri, audit_enabled, audit_back_log, audit_max_payload, audit_repl_patt_type, serialization_type, timeout, sec_tls_ca_cert_id, has_rbac, service_id, cluster_id, security_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' [{'sec_tls_ca_cert_id': None, 'is_internal': False, 'soap_action': u'', 'cluster_id': 1, 'has_rbac': u'', 'serialization_type': u'string', 'ping_method': u'HEAD', 'transport': u'plain_http', 'soap_version': u'', 'method': u'GET', 'is_active': True, 'host': u'', 'security_id': u'', 'url_path': u'\/my-service\/get-key.get-key', 'merge_url_params_req': True, 'name': u'test_channel', 'data_format': u'json', 'pool_size': 20, 'url_params_pri': u'qs-over-path', 'connection': u'channel', 'timeout': 10, 'service_id': 338, 'params_pri': u'channel-params-over-msg'}]\n", "result": "ZATO_ERROR", "cid": "K062ZRHK5VZ39VHBW9580JEVTVG0"}}

**Comment by dsuch** [comment]
Closing older tickets.
