### ISSUE TITLE
Testing zato.kvdb.data-dict.dictionary.* services: Assertion Failed

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato-apitest#12]
Dictionary ids returned by dictionary create and get-last-id services are of different types. This causes problems when we want to compare if id returned by one service the same as the one returned by the other service (they're expected to be the same):

'''
curl --user pubapi:pubapi localhost:11223/zato/json/zato.kvdb.data-dict.dictionary.create -d '{"system":"test_system", "key":"test_key", "value":"test_value"}'

{"zato_env": {"details": "", "result": "ZATO_OK", "cid": "K074AD3N91ACC0XRJPARGTHBX1XK"}, "zato_kvdb_data_dict_dictionary_create_response": {"id": 58}}
'''

In above response we get an integer, but we get a string in response to the following request:

'''
curl --user pubapi:pubapi localhost:11223/zato/json/zato.kvdb.data-dict.dictionary.get-last-id -d '{}'

{"zato_kvdb_data_dict_dictionary_get_last_id_response": {"value": "58"}, "zato_env": {"details": "", "result": "ZATO_OK", "cid": "K061RTCY6DJHYXY8M3AWBS5XD239"}}
'''

Given we write test scenarios:

'''
Scenario: Create data dictionary test entry in a cluster's KVDB 
    Given address "@test_server"
    Given URL path "/zato/json/zato.kvdb.data-dict.dictionary.create"
    Given Basic Auth "@pubapi_user" "@pubapi_password"
    Given format "JSON"
    Given request is "{}"
    Given JSON Pointer "/system" in request is "#test_system"
    Given JSON Pointer "/key" in request is "#test_key"
    Given JSON Pointer "/value" in request is "#test_value"
    When the URL is invoked
    Then JSON Pointer "/zato_env/result" is "ZATO_OK"
    And I store "/zato_kvdb_data_dict_dictionary_create_response/id" from response under "test_dictionary_entry_id"

  Scenario: Invoke get-last-id to check if test dictionary entry actually exists 
    Given address "@test_server"
    Given URL path "/zato/json/zato.kvdb.data-dict.dictionary.get-last-id"
    Given format "JSON"
    When the URL is invoked
    Then JSON Pointer "/zato_env/result" is "ZATO_OK"
    And JSON Pointer "/zato_kvdb_data_dict_dictionary_get_last_id_response/value" is an integer "#test_dictionary_entry_id"
      Assertion Failed: 56 != u'56'
      Captured logging:
      INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): localhost
'''

...we get Assertion Failed.

Using "Then JSON Pointer '{path}' is '{value}'" instead of "Then JSON Pointer '{path}' is an integer '{value}'" doesn't change the situation.

**Comment by dsuch** [comment]
Closing older tickets.
