### ISSUE TITLE
Issue with "Then JSON Pointer "{path}" is/isn't empty" steps

### ISSUE THREAD

**Issue by rafal-k** [zatosource/zato-apitest#16]
I've noticed that each time contents of a JSON Pointer which happens to be an _empty_ list are asserted, _both_ steps:

```
Then JSON Pointer "{path}" is empty
```

and

```
Then JSON Pointer "{path}" isn't empty
```

are passing the test as true. 

For example, given the following response:

```
{"response": {"list_in_question": "", "some_pointer": "OK", "another_pointer": "151"}}
```

Both steps:

```
Then JSON Pointer "/response/list_in_question" is empty
```

and

```
Then JSON Pointer "/response/list_in_question" isn't empty
```

are asserted to be true.

**Comment by dsuch** [comment]
Closing older tickets.
