### ISSUE TITLE
Arrow API DateTimeFormatter  doesn't support Zato datetime format used in sec_wall

### ISSUE THREAD

**Issue by aek** [zatosource/zato-apitest#17]
The underlying API for generate dates in zato-apitest doesn't support  the format used for SOAP dates in sec_wall:
soap_date_time_format = "%Y-%m-%dT%H:%M:%S.%fZ"
Meaning that Arrow can generate this format "%Y-%m-%dT%H:%M:%S.%f" without the "Z" character. Due to this and others reasons I needed to create an step for string format using values from the context, for example to obtain an UTC now date for using in SOAP WS-Security authentication "Created" value I need to do the following

```
    Given I store UTC now under "soap_created" "default"
    Given I store a format string "{soap_created}.000Z" under "soap_created_value"
```

The result is:
soap_created = '2014-12-05T23:30:25'
soap_created_value = '2014-12-05T23:30:25.000Z'

The idea is that you could create a value using composition of others values. This solution is not on the master branch yet but could be helpful to solve others scenarios like the generation of url for channels without a dedicated steps for that. Something like this:

```
    Given I store a random string under "url_path1"
    Given I store a random string under "url_path2"
    Given I store a format string "/{url_path1}/{url_path2}.action" under "action_url"
```

That is a random url composed by 2 randoms strings

Hope this helps

**Comment by dsuch** [comment]
Mass-closing old tickets.
