### ISSUE TITLE
Broken unit test

### ISSUE THREAD

**Issue by lcosmin** [zatosource/zato-apitest#22]
There are cases when the `test_then_json_pointer_is_an_integer` test fails.

Look at: https://github.com/zatosource/zato-apitest/blob/master/test/zato/apitest/steps/test_json.py#L141

``` python
    def test_then_json_pointer_is_an_integer(self):
        path, value = util.rand_string(2)
        value = util.rand_int()
        self.ctx.zato.response.data_impl[path] = util.rand_int()
        self.assertRaises(AssertionError, json.then_json_pointer_is_an_integer, self.ctx, '/' + path, value)
```

First of all, I don't see the point of assigning to value in the first line. 
The bug occurs when `util.rand_int()` generates the same random number for both `value` and `self.ctx.zato.response.data_impl[path]`, in which case the assert fails (no exception raised).

Not sure if there are more tests with this issue, haven't checked.

**Comment by dsuch** [comment]
Hm, you are right - value should not be obtained twice.

And to work around the random integers getting the same value - *util.rand_int* accepts min/max parameters, so each call could specify different range to ensure they don't overlap.

Do you think you could contribute a fix? Thanks.

**Comment by lcosmin** [comment]
Opened a pull request.
Btw, I wanted to ask,  is there any reason why `util.rand_int` is written the way it is instead of using `random.randint` ?

**Comment by dsuch** [comment]
Closing older tickets.
