### ISSUE TITLE
Add a way to test an individual feature

### ISSUE THREAD

**Issue by Cito** [zatosource/zato-apitest#28]
It seems that currently you can only run the whole test suite with the `apitest run` command.

The command should take optional feature name(s) as additional parameter(s) and test only these features if any additional parameter is given.

**Comment by dsuch** [comment]
Yes, that makes sense. Do you perhaps know if behave itself supports it?

**Comment by Cito** [comment]
Did a bit research. Behave has the `-e` and `-i` Options to exclude and include certain features. If you put these in the config.ini file, it should work. Maybe the best solution would be to just merge the command line args to the configuration file? I can check it out next week and submit a pull request unless you want to do it yourself.

**Comment by dsuch** [comment]
Hi @Cito - please proceed if you can. Unfortunately, I won't have time for it myself. Thanks!

**Comment by Cito** [comment]
See pull request #30

**Comment by dsuch** [comment]
Hi @Cito - I saw it yesterday. I've only got a few remarks and would like to change some trivial things myself but the PR looks really good, thanks!

I'm just swamped at work and won't be able to merge it for a few days more.

But I really thank you, this was a very needed feature! :)

**Comment by dsuch** [comment]
By the way, why is behave.ini config.ini now?

**Comment by Cito** [comment]
> By the way, why is behave.ini config.ini now?

As far as I see it is a change you made last year in cddae21ef4865166 - I just adapted the README to reflect that change.It was also moved from a separate config directory into the features directory.

**Comment by dsuch** [comment]
Hahaha, sorry, you are right :)

**Comment by dsuch** [comment]
Closing older tickets.
