### ISSUE TITLE
obtain_values cannot mix text and variables

### ISSUE THREAD

**Issue by thomasez** [zatosource/zato-apitest#32]
When using the config_functions (@,$,#) they have to be alone in a test parameter. This is what I'd like to have:

`Given URL path "/item/#item_id/edit"`

The problem here is of course to find the variables within the path. Here it is #item_id. This could be done in two ways.

The first is to search for the config function characters and then see if there are a match against any known config variable, if true, replace.

The second option is to use some sort of templating like Jinja or (somehow) support Format Specification.

Right now I am doing a third option, `@given('I add "{value}" to the URL path')` which has no place in the apitest code as it is too ugly, but works.

I'd like .format somehow, but have no idea how to implement it (at least not yet) so no PR from me in this case unfortunately.

**Comment by dsuch** [comment]
Mass-closing old tickets.
