### ISSUE TITLE
Make it easy to debug tests and API by printing request and response details

### ISSUE THREAD

**Issue by pixelogik** [zatosource/zato-apitest#44]
I miss the option to print detailed request and reponse information to the console. 

This way it is really hard to debug / develop tests. 

Is there already a feature for this? @dsuch

**Comment by dsuch** [comment]
Thanks @pixelogik - yes, this totally makes sense. What would we log - full exception, request, response, timestamp for sure. Anything else you can think of?

**Comment by pixelogik** [comment]
@dsuch Nice! Yeah sounds good. For writing and debugging the tests I would mainly need request and response fully (header, body). Can't think of anything else at this moment.

**Comment by pixelogik** [comment]
@dsuch This apitest tool is btw really awesome! I wrote something like this myself, but yours is much more powerful. With the log feature this is perfect, without really hard to use at this point. 

If you need help with development, I might find some time in the next weeks to help out. But would then need pointers to what to do.

**Comment by pixelogik** [comment]
@dsuch Do you have a time plan for this? I would help out if that is needed. I really want to use this tool but without that feature it is a bit useless.

**Comment by dsuch** [comment]
Hi @pixelogik,

I got carried away with other tasks at work - yes, let's do it.

Best thing I reckon would be for you to add a kind of a try/except block around the code that invokes HTTP endpoints. Upon catching any exceptions, log information about what was sent to the remote end (both headers and body) as well as what exactly was received (again, headers and body).

Does that sound right to you?

**Comment by pixelogik** [comment]
@dsuch Almost. I want to be able to print out stuff even if nothing fails! So this reporting feature should be independent on the outcome of the request. 

If you point me to the code location where requests are done and what data structures and properties I could print, that would help a lot.

**Comment by dsuch** [comment]
Sure, please feel free to look around here:

https://github.com/zatosource/zato-apitest/blob/master/src/zato/apitest/steps/common.py#L42

The function that actually invokes HTTP endpoints is called 'when_the_url_is_invoked'. Parameter 'ctx' contains everything that is related to outgoing requests and responses - you will find everything that is needed in that function I believe.

**Comment by dsuch** [comment]
Hi @pixelogik,

I will need this functionality myself soon - if you don't have a PR, this is fine, I will implement the feature myself.

Regards.

**Comment by dsuch** [comment]
Mass-closing old tickets.
